import { Inventory } from "@types";

export const inventory: Inventory[] = [
  {
    id: 0, 
    hash: "0",
    pfp: ["/images/hotheads/hothead_character_000.png" ],
    banners:["/images/hotheads/hothead_character_003.png" ],
    wallpapers: ["/images/hotheads/hothead_character_004.png"],
    memes:["/images/hotheads/hothead_character_005.png" ],
  },
  {
    id: 1, 
    hash: "1",
    pfp: ["/images/hotheads/hothead_character_001.png" ],
    banners:["/images/hotheads/hothead_character_006.png" ],
    wallpapers: ["/images/hotheads/hothead_character_007.png"],
    memes:["/images/hotheads/hothead_character_008.png" ],
  },
  {
    id: 2, 
    hash: "2",
    pfp: ["/images/hotheads/hothead_character_002.png" ],
    banners:["/images/hotheads/hothead_character_009.png" ],
    wallpapers: ["/images/hotheads/hothead_character_010.png"],
    memes:["/images/hotheads/hothead_character_011.png" ],
  },
  {
    id: 3, 
    hash: "3",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 4, 
    hash: "Hot Head #004",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 5, 
    hash: "Hot Head #005",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 6, 
    hash: "Hot Head #006",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 7, 
    hash: "Hot Head #007",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 8, 
    hash: "Hot Head #008",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 9, 
    hash: "Hot Head #009",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 10, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 11, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 12, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 13, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 14, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 15, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 16, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id:17, 
    hash: "Hot Head #01",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 18, 
    hash: "Hot Head #018",
    pfp: ["/images/hotheads/hothead_character_018.png" ],
    banners:["/images/hotheads/hothead_character_018.png" ],
    wallpapers: ["/images/hotheads/hothead_character_018.png"],
    memes:["/images/hotheads/hothead_character_018.png" ],
  },
];