import { Inventory } from "@types";

export const inventory: Inventory[] = [
  {
    id: 0, // ** hot head number **
    hash: "",
    pfp: ["/images/hotheads/hothead_character_000.png" ],
    banners:["/images/hotheads/hothead_character_003.png" ],
    wallpapers: ["/images/hotheads/hothead_character_004.png"],
    memes:["/images/hotheads/hothead_character_005.png" ],
  },
  {
    id: 1, // ** hot head number **
    hash: "",
    pfp: ["/images/hotheads/hothead_character_001.png" ],
    banners:["/images/hotheads/hothead_character_006.png" ],
    wallpapers: ["/images/hotheads/hothead_character_007.png"],
    memes:["/images/hotheads/hothead_character_008.png" ],
  },
  {
    id: 2, // ** hot head number **
    hash: "",
    pfp: ["/images/hotheads/hothead_character_002.png" ],
    banners:["/images/hotheads/hothead_character_009.png" ],
    wallpapers: ["/images/hotheads/hothead_character_010.png"],
    memes:["/images/hotheads/hothead_character_011.png" ],
  },
  {
    id: 3, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 4, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 5, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 6, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 7, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 8, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 9, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 10, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 11, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 12, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 13, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 14, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 15, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 16, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id:17, 
    hash: "",
    pfp: [],
    banners:[],
    wallpapers: [],
    memes:[],
  },
  {
    id: 18, 
    hash: "",
    pfp: ["/images/hotheads/hothead_character_018.png" ],
    banners:["/images/hotheads/hothead_character_018.png" ],
    wallpapers: ["/images/hotheads/hothead_character_018.png"],
    memes:["/images/hotheads/hothead_character_018.png" ],
  },
];